#version: "3.8"
#services:
#  db:
#    image: postgres:15
#    environment:
#      POSTGRES_DB: fantasy
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#  web:
#    build: .
#    command: gunicorn project_name.wsgi:application --bind 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#volumes:
#  postgres_data:


version: "3.9"

services:
  db:
    image: postgres:15
    container_name: fantasy_db
    environment:
      POSTGRES_DB: fantasy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: fantasy_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: fantasy
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432


  test:
    build: .
    container_name: fantasy_test
    command: pytest --disable-warnings -q
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      DB_NAME: fantasy
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: project_name.settings  # replace with your real settings

volumes:
  postgres_data:
